version: '3.8'
services:
  email-capture-receiver:
    build: .
    image: email-capture-receiver
    container_name: email-capture-receiver
    depends_on:
      - email-capture-postgres
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
      TOPIC_NAME: ${TOPIC_NAME}
      SUBSCRIPTION_NAME: ${SUBSCRIPTION_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}

  email-capture-postgres:
      image: postgres:11.4-alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      ports:
        - "5432:5432" 
      volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
